### ISSUE TITLE
Unmarshalling cell with SpreadsheetError fails

### ISSUE THREAD

**Issue by mP1** [mP1/walkingkooka-spreadsheet-react#1641]
```json
"value": {
          "type": "spreadsheet-error",
          "value": {
            "kind": "REF",
            "message": "Reference not found: B3"
          }
        }
```

```
index.js:1350 fetch failed, using /api/spreadsheet/2/cell/A1 with {"method":"PATCH","body":"{\"cells\":{\"A1\":{\"formula\":{\"text\":\"=1+2+b3\"}}}}","headers":{"Accept":"application/json","Accept-Charset":"UTF-8","Content-Type":"application/json;charset=UTF-8","X-Transaction-ID":"18"}}
Error: Expected string message got [object Object] Error: Expected string message got [object Object]
    at reportError (Preconditions.js:2:1)
    at Function.requireText (Preconditions.js:101:1)
    at Function.requireNonEmptyText (Preconditions.js:111:1)
    at new SpreadsheetError (SpreadsheetError.js:17:1)
    at fromJson (SpreadsheetError.js:12:1)
    at Function.fromJsonWithType (SystemObject.js:49:1)
    at Function.fromJson (SpreadsheetFormula.js:21:1)
    at Function.fromJson (SpreadsheetCell.js:50:1)
    at SpreadsheetMessengerCrud.fromJson [as unmarshall] (SpreadsheetDelta.js:40:1)
```

**Comment by mP1** [comment]
Json format should be

```json
{
   "kind": SpreadsheetErrorKind
    "message": String
}
```
